-- Catalog seed data. Run AFTER 01_schema.sql.

-- colors
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-050','Frost MCT-050','#F2F2F0','a bright frost white with the faintest cool grey shadowing',10,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-100','Eclipse MCT-100','#5A5F5E','a deep eclipse charcoal grey with cool tonal depth',20,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-120','Solace MCT-120','#7E8478','a mid solace grey with a soft muted green-grey cast',30,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-140','Veil MCT-140','#8A8B7A','a veil grey-olive with a gentle earthy haze',40,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-200','Dune MCT-200','#9A8F6B','a warm dune khaki with sandy golden undertones',50,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-220','Terra MCT-220','#8E6A4E','a rich terra brown with warm toasted earth tones',60,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-240','Husk MCT-240','#8E6558','a husk brown with soft rosy-mauve warmth',70,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-300','Shiraz MCT-300','#8C3B3E','a deep shiraz red with wine-like richness',80,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-320','Flame MCT-320','#B8453A','a vivid flame terracotta red',90,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-400','Moss MCT-400','#8FA282','a soft moss sage green',100,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-420','Meadow MCT-420','#1FB08A','a vibrant meadow emerald green with fresh clarity',110,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-500','Lagoon MCT-500','#4C9BE8','a clear lagoon sky blue',120,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-520','Aquamarine MCT-520','#3E7789','a deep aquamarine teal blue',130,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-600','Lavender MCT-600','#8258C8','a rich lavender violet',140,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-700','Marigold MCT-700','#E5854A','a warm marigold orange',150,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.colors (id,name,hex,prompt_fragment,sort_order,active) VALUES ('mct-800','Sunset MCT-800','#EFC069','a golden sunset yellow',160,true) ON CONFLICT (id) DO NOTHING;

-- textures
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('rame-patina','Rame Patina','A warm copper finish with an oxidised patina effect.','#a8563a','a warm copper metallic micro cement finish with an oxidised verdigris patina, rust and turquoise mineral bloom, hand-trowelled movement',1,true,'/__l5e/assets-v1/4a62b494-6140-4ce2-939c-29aa75fc0546/rame-patina.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('azzurro-linea','Azzurro Linea','Deep ocean blue with fine vertical brush lines.','#1f5f8b','a deep ocean blue micro cement finish with fine vertical raked brush lines and subtle tonal depth',2,true,'/__l5e/assets-v1/349c094d-b887-4b92-b142-feec3d066617/azzurro-linea.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('terra-toscana','Terra Toscana','Rustic terracotta with layered movement.','#b5623f','a rustic Tuscan terracotta micro cement finish with layered trowel movement and warm earthen mottling',3,true,'/__l5e/assets-v1/340dffa8-8106-4807-96c8-b590122c4400/terra-toscana.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('sabbia-fine','Sabbia Fine','Fine sand-textured finish in a soft beige.','#d9c7a7','a fine sand-textured micro cement finish in a soft warm beige with delicate pitting and even grain',4,true,'/__l5e/assets-v1/e5388f7e-8d59-4a2f-a275-218b44970928/sabbia-fine.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('coccodrillo','Coccodrillo','Crocodile skin-inspired textured finish.','#b48b4a','a crocodile skin inspired textured micro cement finish with raised scale patterning in warm golden tan',5,true,'/__l5e/assets-v1/099ce485-e439-4821-bb36-52d9285283da/coccodrillo.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('oro-spazzolato','Oro Spazzolato','Brushed gold metallic with subtle shimmer.','#c9a45c','a brushed gold metallic micro cement finish with horizontal brush strokes and a subtle shimmering sheen',6,true,'/__l5e/assets-v1/70c24016-3cf8-4e63-b4a1-154df30fb182/oro-spazzolato.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('marmo-rosa','Marmo Rosa','Grey marble with blush-pink veining.','#c9a3a0','a grey marble effect micro cement finish with soft blush pink veining and cloudy stone movement',7,true,'/__l5e/assets-v1/34c9b41e-f645-4a07-8093-6fb1fc9e830a/marmo-rosa.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('cemento-naturale','Cemento Naturale','Soft natural concrete effect.','#b9b5ae','a soft natural concrete effect micro cement finish in light warm grey with gentle cloudy movement',8,true,'/__l5e/assets-v1/896d26ce-5708-45f8-ba59-c99b25bce8a2/cemento-naturale.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('oro-antico','Oro Antico','Antique brushed gold finish.','#c1934f','an antique brushed gold micro cement finish with aged sandy golden tones and soft trowel seams',9,true,'/__l5e/assets-v1/39e740fb-b225-4b4d-bb89-565637eed4ab/oro-antico.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('corallo-veneziano','Corallo Veneziano','Venetian plaster with warm coral tones.','#c86a55','a Venetian plaster micro cement finish with warm coral and terracotta tones and polished trowel marks',10,true,'/__l5e/assets-v1/19bd114c-8091-4f4d-89c6-5547f793b1c0/corallo-veneziano.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('champagne-velvet','Champagne Velvet','Soft champagne metallic finish.','#dcc49a','a soft champagne metallic micro cement finish with a velvety sheen and cloudy trowel movement',11,true,'/__l5e/assets-v1/b2693915-5597-402c-85cc-c17c87280720/champagne-velvet.jpg') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.textures (id,name,description,swatch_color,prompt_fragment,sort_order,active,image_url) VALUES ('argento-seta','Argento Seta','Silver silk with elegant horizontal movement.','#c3c6c8','a silver silk metallic micro cement finish with elegant horizontal movement and a satin shimmer',12,true,'/__l5e/assets-v1/bccad704-be8a-4abd-a5ec-58f7c6a21fa2/argento-seta.jpg') ON CONFLICT (id) DO NOTHING;

-- products
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('training-diy-workshop','DIY Micro Cement Training — 22 August 2026',770.00,'Training','https://www.jotform.com/uploads/5Y_studio/form_files/m520_microestil_plus_base_25kg_954b830b2aa43c9da28f4d9cc6aff1b1.png','Full-day hands-on micro cement workshop at our Malaga warehouse. All materials, tools and lunch included.','A full day on the trowel with Maurizio and the Cemento team: substrate prep, priming, mixing, trowel technique, tinting, sanding and sealing. Small groups so everyone gets their own practice panel.','One participant place','per person',20,0,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m520','Microestil Plus Base 25kg',308.00,'Micro cement','https://www.jotform.com/uploads/5Y_studio/form_files/m520_microestil_plus_base_25kg_954b830b2aa43c9da28f4d9cc6aff1b1.png','Two-coat base layer for walls and floors. Covers roughly 25–30m² per bag.',NULL,NULL,NULL,100,10,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m522','Microestil Plus Fino 20kg',364.00,'Micro cement','https://www.jotform.com/uploads/5Y_studio/form_files/microcement_fino_20kg_m522_2_1_300x225_bfd7838ae22af2f906736810f4c61313.png','Fine-grain finishing coat for silky smooth, low-texture surfaces.',NULL,NULL,NULL,100,20,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m521','Microestil Plus Medio 20kg',291.00,'Micro cement','https://www.jotform.com/uploads/5Y_studio/form_files/microcement_medio_20kg_m521_300x225_ec34dddf21abe86f6b62c2fdabaf9967.png','Medium-grain coat for floors and hard-wearing textured finishes.',NULL,NULL,NULL,100,30,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('mct050','MCT-050 Blanco 250ml',83.00,'Pigments','https://www.jotform.com/uploads/5Y_studio/form_files/mct_050_4_1_300x225_9f6caf90ace1e6f2ce9ae0955bf88174.png','Concentrated white tint for Microestil base and finishing coats.',NULL,NULL,NULL,100,40,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('mct100','MCT-100 Negro 250ml',74.00,'Pigments','https://www.jotform.com/uploads/5Y_studio/form_files/mct_100_4_300x225_264abce33f8aef35bbf5e97e5488568a.png','Deep black tint for charcoal and graphite colour matching.',NULL,NULL,NULL,100,50,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('mct120','MCT-120 Calido 250ml',74.00,'Pigments','https://www.jotform.com/uploads/5Y_studio/form_files/mct_120_4_300x225_9960c2bd8ad71372b1dc95cdbf67ded3.png','Warm neutral tint for sand and limestone tones.',NULL,NULL,NULL,100,60,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('mct140','MCT-140 Sombra 250ml',74.00,'Pigments','https://www.jotform.com/uploads/5Y_studio/form_files/mct_140_4_300x225_8750ba2dee415d0b93ee34e8de4956af.png','Shadow grey tint for cool contemporary greys.',NULL,NULL,NULL,100,70,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('mct200','MCT-200 Crema 250ml',74.00,'Pigments','https://www.jotform.com/uploads/5Y_studio/form_files/mct_200_4_300x225_fcfb9273e3faa8b91fb25cdc79a56011.png','Soft cream tint for bright, airy interiors.',NULL,NULL,NULL,100,80,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('mct240','MCT-240 Marron 250ml',74.00,'Pigments','https://www.jotform.com/uploads/5Y_studio/form_files/mct_240_4_300x225_ca5fb6e81c1d00e2f1050b36458731e6.png','Rich brown tint for earthy, terracotta-leaning finishes.',NULL,NULL,NULL,100,90,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m564-1','Porous Surface Primer 1 Litre',13.77,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m564_porous_surface_primer_1l_square_300x225_7a46139cdeca7eafdd8c993d47545787.png','Bonding primer for plasterboard, render and other absorbent substrates.',NULL,NULL,NULL,100,100,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m564-4','Porous Surface Primer 4 Litre',46.73,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m5644_porous_surface_primer_4l_square_300x225_f812c89ec6ddcb2d404e0ef69ebf3a44.png','Bulk bonding primer for absorbent substrates on larger jobs.',NULL,NULL,NULL,100,110,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m562','Smooth Surface Primer 1 Litre',33.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m562_microestil_smooth_1l_square_300x225_ca9c613d08472b46fcfc197c687fa8d5.png','Grip primer for tile, glass and other non-absorbent surfaces.',NULL,NULL,NULL,100,120,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m563','Smooth Surface Primer 4 Litre',100.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m563_microestil_smooth_4l_square_300x225_244f59a42d3102696b683151319b52eb.png','Bulk grip primer for tile and non-absorbent substrates.',NULL,NULL,NULL,100,130,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m560','Microestil Microshield 1 Litre',35.50,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m560_microestil_microshield_1l_square_300x225_95431b4a01521f0b9127ddc918e4899a.png','Protective sealer coat that locks in colour and repels staining.',NULL,NULL,NULL,100,140,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m561','Microestil Microshield 4 Litre',109.09,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m561_microestil_microshield_4l_square_300x225_e1c785d8870672e946a696ddcc31eeb5.png','Bulk protective sealer for full-home applications.',NULL,NULL,NULL,100,150,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m570','Superiorseal Primer 1kg',33.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m570_superiorseal_primer_1kg_square_300x225_7f4bcfd92669873f1bd50ab6938aa029.png','High-performance primer coat for the Superiorseal system.',NULL,NULL,NULL,100,160,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m571','Superiorseal Primer 5kg',115.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m571_superiorseal_primer_5kg_square_1_300x225_548dabd50771605ca4278740af23634f.png','Bulk primer coat for the Superiorseal two-pack system.',NULL,NULL,NULL,100,170,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m573','Superiorseal Gloss Part A 800g',38.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m573_gloss_part_a_800g_square_300x225_057d1b4840c9ef3d3e822a9ed08dccdc.png','Gloss two-pack topcoat, part A. Pair with Part B hardener.',NULL,NULL,NULL,100,180,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m574','Superiorseal Gloss Part A 4kg',118.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m574_gloss_kit_part_a_4kg_square_300x225_658bf476cf8c0ce18d8f98bb15755dc3.png','Bulk gloss two-pack topcoat, part A.',NULL,NULL,NULL,100,190,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m576','Superiorseal Matt Part A 800g',42.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m576_matte_part_a_800g_square_1_300x225_114d962efcdd1b474401b44024ccac59.png','Matt two-pack topcoat, part A. Pair with Part B hardener.',NULL,NULL,NULL,100,200,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m577','Superiorseal Matt Part A 4kg',128.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m577_matte_part_a_4kg_square_300x225_30676273c7282ee4c4dff98eb274c6b5.png','Bulk matt two-pack topcoat, part A.',NULL,NULL,NULL,100,210,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m578','Superiorseal 2K Part B 200g',21.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m578_superiorseal_hardener_part_b_200g_square_300x225_b1b6acb86e0264e4505f46dc1f82a81f.png','Hardener for 800g Superiorseal gloss or matt topcoats.',NULL,NULL,NULL,100,220,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('m579','Superiorseal 2K Part B 1kg',68.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m579_superiorseal_hardener_part_b_1kg_front_square_1_300x225_00edf0e121383452cb9c195e6b717a7b.png','Hardener for 4kg Superiorseal gloss or matt topcoats.',NULL,NULL,NULL,100,230,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('wb2k-8','WB2K Part 1 & 2 — 8 Litre Kit',190.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m565_wb2k_epoxy_sealer_part_1_2_4l_square_300x225_b23933723fefd69d524aab15656f042b.png','Water-based two-pack epoxy sealer kit for floors and wet areas.',NULL,NULL,NULL,100,240,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('wb2k-20','WB2K Part 1 & 2 — 20 Litre Kit',330.00,'Primers & sealers','https://www.jotform.com/uploads/5Y_studio/form_files/m565_wb2k_epoxy_sealer_part_1_2_10l_square_v2_300x225_3c05489b59a68c06ef108495769c9202.png','Large water-based two-pack epoxy sealer kit for commercial jobs.',NULL,NULL,NULL,100,250,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('syringe-20','20ml Luer Lock Syringe',1.82,'Accessories','https://www.jotform.com/uploads/5Y_studio/form_files/download_43f31079b8ef5f20c6faec1ba1ea2156.jpg','For accurate pigment dosing when colour matching.',NULL,NULL,NULL,100,260,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,category,image,description,long_description,coverage,unit,stock,sort_order,active) VALUES ('syringe-60','60ml Luer Lock Syringe',3.64,'Accessories','https://www.jotform.com/uploads/5Y_studio/form_files/00025162_da525eda8c75483db41f48593bf6cb02.jpg','Larger syringe for dosing pigment into full batches.',NULL,NULL,NULL,100,270,true) ON CONFLICT (id) DO NOTHING;
